version: 2

project_name: terraform-provider-aws

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-aws
    binary: terraform-provider-aws
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: provider-archive
    format: zip
    name_template: "terraform-provider-aws_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "terraform-provider-aws_{{ .Version }}_SHA256SUMS"

# IMPORTANT: sign ONLY the checksum (Terraform Registry requirement)
signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - --batch
      - --yes
      - --pinentry-mode=loopback
      - --passphrase=${GPG_PASSPHRASE}
      - --local-user=${GPG_KEY_ID}
      - --output
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: BelianBooker
    name: terraform-provider-aws

changelog:
  sort: asc
