version: 2

project_name: terraform-provider-aws

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-aws
    binary: terraform-provider-aws
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: plugin-archives
    format: zip
    name_template: "terraform-provider-aws_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "terraform-provider-aws_{{ .Version }}_SHA256SUMS"

signs: []   # <-- IMPORTANT: disables signatures = no SHASUMS sig warning

release:
  github:
    owner: BelianBooker
    name: terraform-provider-aws
    draft: false
    prerelease: false

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
