version: 2

project_name: terraform-provider-aws

before:
  hooks:
    - go mod tidy

builds:
  - id: aws
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    builds:
      - aws

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'

signs:
  - cmd: gpg
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--armor"
      - "--detach-sign"
      - "--output"
      - "${signature}"
      - "${artifact}"

release:
  github:
    owner: BelianBooker
    name: terraform-provider-aws
